add update json script
Signed-off-by: smallyunet <dev.wangyu@gmail.com>

diff --git a/.github/workflows/publish-release-docker.yml b/.github/workflows/publish-release-docker.yml
--- a/.github/workflows/publish-release-docker.yml
+++ b/.github/workflows/publish-release-docker.yml
@@ -75,16 +75,46 @@ jobs:
           docker pull docker.io/pellnetwork/pellnode:${GORELEASER_CURRENT_TAG}
 
           CONTAINER_ID=$(docker create docker.io/pellnetwork/pellnode:${GORELEASER_CURRENT_TAG})
-          docker cp $CONTAINER_ID:/usr/local/bin/pellcored ./pellcored
+          docker cp $CONTAINER_ID:/usr/local/bin/pellcored ./pellcored-${NEW_VERSION}-linux-amd64
           docker rm $CONTAINER_ID
 
-          sha256sum pellcored > checksums.txt
+          sha256sum pellcored-${NEW_VERSION}-linux-amd64 > checksums.txt
 
           mkdir -p release
-          mv pellcored release/
+          mv pellcored-${NEW_VERSION}-linux-amd64 release/
           mv checksums.txt release/
 
           gh release upload "${GORELEASER_CURRENT_TAG}" release/*
+
+      - name: Update binary_list.json
+        run: |
+          JSON_FILE="testnet/binary_list.json"
+          NEW_VERSION="${GORELEASER_CURRENT_TAG}"
+          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/${NEW_VERSION}/pellcored-${NEW_VERSION}-linux-amd64"
+          BINARY_LOCATION="cosmovisor/upgrades/${NEW_VERSION}/bin/pellcored"
+
+          if [ ! -f "$JSON_FILE" ]; then
+            echo "Error: $JSON_FILE not found!"
+            exit 1
+          fi
+
+          cp "$JSON_FILE" "${JSON_FILE}.bak"
+
+          jq --arg url "$DOWNLOAD_URL" --arg loc "$BINARY_LOCATION" '.binaries += [{"download_url": $url, "binary_location": $loc}]' "$JSON_FILE" > temp.json && mv temp.json "$JSON_FILE"
+
+          echo "Updated $JSON_FILE:"
+          cat "$JSON_FILE"
+
+      - name: Commit and Push Changes
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+
+          git add testnet/binary_list.json
+          git commit -m "Update binary_list.json with version ${GORELEASER_CURRENT_TAG}"
+          git push origin HEAD:${{ github.ref_name }}
 
       - name: Clean Up Workspace
         if: always()
